service:
  name: build-my-backend

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  memorySize: 256
  timeout: 60
  environment:
    DOMAIN_NAME: ${file(./secrets.json):${opt:stage}.DOMAIN_NAME}
    ORGANIZATIONS_TABLE: ${self:custom.DYNAMODB.ORGANIZATIONS_TABLE}
    ORGANIZATIONS_SOURCE_INDEX: ${self:custom.DYNAMODB.ORGANIZATIONS_SOURCE_INDEX}
    EVENTS_TABLE: ${self:custom.DYNAMODB.EVENTS_TABLE}
    EVENTS_STATUS_INDEX: ${self:custom.DYNAMODB.EVENTS_STATUS_INDEX}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: 
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.OrganizationsTable}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.OrganizationsSourceIndex}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.EventsTable}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.EventsStatusIndex}

functions:
  facebookEvent:
    handler: src/handler.facebookEvent
  meetupOrganization:
    handler: src/handler.meetupOrganization
  meetupAllOrganizations:
    handler: src/handler.meetupAllOrganizations
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
  expressHandler:
    handler: src/handler.expressHandler
    events:
      - http:
          path: graphql
          method: get
      - http:
          path: graphql
          method: post
  updateEventsUpcomingToPast:
    handler: src/custom.updateEventsUpcomingToPast
    events:
      # Goal is to do it in the morning MYT time,
      # so that if you are looking at it past midnight it'll still be relevant
      - schedule:
          rate: cron(0 0 * * ? *)
  createEvent:
    handler: src/custom.createEvent

resources:
  Resources:
    # https://github.com/serverless/serverless/issues/2445#issuecomment-333016523
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${opt:stage}
    ProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        PathPart: '{proxy+}'
        RestApiId:
          Ref: ApiGatewayRestApi
    ProxyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Ref: ProxyResource
        RestApiId:
          Ref: ApiGatewayRestApi
        HttpMethod: GET
        MethodResponses:
          - StatusCode: 200
        RequestParameters:
          method.request.path.proxy: true
        AuthorizationType: NONE
        Integration:
          IntegrationHttpMethod: GET
          Type: HTTP_PROXY
          Uri: 'http://build.my.s3-website-us-east-1.amazonaws.com/{proxy}'
          PassthroughBehavior: WHEN_NO_MATCH
          IntegrationResponses:
            - StatusCode: 200
          RequestParameters:
            integration.request.path.proxy: 'method.request.path.proxy'
    RootMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        RestApiId:
          Ref: ApiGatewayRestApi
        HttpMethod: GET
        MethodResponses:
          - StatusCode: 200
        RequestParameters:
          method.request.path.proxy: true
        AuthorizationType: NONE
        Integration:
          IntegrationHttpMethod: GET
          Type: HTTP_PROXY
          Uri: 'http://build.my.s3-website-us-east-1.amazonaws.com/'
          PassthroughBehavior: WHEN_NO_MATCH
          IntegrationResponses:
            - StatusCode: 200
  Outputs:
    CustomEventARN:
      Description: The ARN for the createEvent Lambda
      Value:
        "Fn::GetAtt": [ CreateEventLambdaFunction, Arn ]
      Export:
        Name: ${self:service}:${opt:stage}:CustomEventARN

custom:
  DYNAMODB: ${file(./../dynamodb/tables.js)}
  customDomain:
    domainName: ${self:provider.environment.DOMAIN_NAME}
    basePath: ${file(./secrets.json):${opt:stage}.BASE_PATH, 'false'}
    stage: ${opt:stage}
    createRoute53Record: true
    enabled: ${file(./secrets.json):${opt:stage}.CUSTOM_DOMAIN_ENABLED, 'false'}
  serverless-offline:
    port: 3001
