service:
  name: build-my-backend

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  memorySize: 256
  timeout: 30
  environment:
    DOMAIN_NAME: ${file(./secrets.json):${opt:stage}.DOMAIN_NAME}
    ORGANIZATIONS_TABLE: ${self:custom.DYNAMODB.ORGANIZATIONS_TABLE}
    ORGANIZATIONS_SOURCE_INDEX: ${self:custom.DYNAMODB.ORGANIZATIONS_SOURCE_INDEX}
    ORGANIZATIONS_STATUS_INDEX: ${self:custom.DYNAMODB.ORGANIZATIONS_STATUS_INDEX}
    EVENTS_TABLE: ${self:custom.DYNAMODB.EVENTS_TABLE}
    EVENTS_START_TIME_INDEX: ${self:custom.DYNAMODB.EVENTS_START_TIME_INDEX}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.OrganizationsTable}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.OrganizationsSourceIndex}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.OrganizationsStatusIndex}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.EventsTable}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.EventsStartTimeIndex}
  tags:
    product: build-my-${opt:stage}

functions:
  expressHandler:
    handler: src/handler.expressHandler
    events:
      - http:
          path: graphql
          method: get
      - http:
          path: graphql
          method: post

resources:
  Resources:
    # https://github.com/serverless/serverless/issues/2445#issuecomment-333016523
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${opt:stage}
    ProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        PathPart: '{proxy+}'
        RestApiId:
          Ref: ApiGatewayRestApi
    ProxyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Ref: ProxyResource
        RestApiId:
          Ref: ApiGatewayRestApi
        HttpMethod: GET
        MethodResponses:
          - StatusCode: 200
        RequestParameters:
          method.request.path.proxy: true
        AuthorizationType: NONE
        Integration:
          IntegrationHttpMethod: GET
          Type: HTTP_PROXY
          Uri: ${file(./secrets.json):${opt:stage}.S3_BUCKET}/{proxy}
          PassthroughBehavior: WHEN_NO_MATCH
          IntegrationResponses:
            - StatusCode: 200
          RequestParameters:
            integration.request.path.proxy: 'method.request.path.proxy'
    RootMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        RestApiId:
          Ref: ApiGatewayRestApi
        HttpMethod: GET
        MethodResponses:
          - StatusCode: 200
        RequestParameters:
          method.request.path.proxy: true
        AuthorizationType: NONE
        Integration:
          IntegrationHttpMethod: GET
          Type: HTTP_PROXY
          Uri: ${file(./secrets.json):${opt:stage}.S3_BUCKET}/
          PassthroughBehavior: WHEN_NO_MATCH
          IntegrationResponses:
            - StatusCode: 200

custom:
  DYNAMODB: ${file(./../dynamodb/tables.js)}
  customDomain:
    domainName: ${self:provider.environment.DOMAIN_NAME}
    basePath: ${file(./secrets.json):${opt:stage}.BASE_PATH, 'false'}
    stage: ${opt:stage}
    createRoute53Record: true
    enabled: ${file(./secrets.json):${opt:stage}.CUSTOM_DOMAIN_ENABLED, 'false'}
  serverless-offline:
    port: 3001
