service: build-my-lambdas

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  timeout: 60
  environment:
    ORGANIZATIONS_TABLE: ${self:custom.DYNAMODB.ORGANIZATIONS_TABLE}
    ORGANIZATIONS_SOURCE_INDEX: ${self:custom.DYNAMODB.ORGANIZATIONS_SOURCE_INDEX}
    ORGANIZATIONS_STATUS_INDEX: ${self:custom.DYNAMODB.ORGANIZATIONS_STATUS_INDEX}
    EVENTS_TABLE: ${self:custom.DYNAMODB.EVENTS_TABLE}
    EVENTS_END_TIME_INDEX: ${self:custom.DYNAMODB.EVENTS_END_TIME_INDEX}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:BatchWriteItem
      Resource:
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.OrganizationsTable}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.OrganizationsSourceIndex}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.OrganizationsStatusIndex}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.EventsTable}
        - ${cf.ap-southeast-1:build-my-dynamodb-${opt:stage}.EventsEndTimeIndex}
  tags:
    product: build-my-${opt:stage}

package:
  include:
    - src/**/*

functions:
  facebookOrganization:
    handler: src/handler.facebookOrganization
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - "arn:aws:ssm:${opt:region}:*:parameter/build.my/${opt:stage}/FACEBOOK_ACCESS_TOKEN"
  meetupOrganization:
    handler: src/handler.meetupOrganization
  meetupAllOrganizations:
    handler: src/handler.meetupAllOrganizations
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
  peatix:
    handler: src/scrapers.peatix
  updateEventsUpcomingToPast:
    handler: src/custom.updateEventsUpcomingToPast
    events:
      # Goal is to do it in the morning MYT time,
      # so that if you are looking at it past midnight it'll still be relevant
      - schedule:
          rate: cron(0 0 * * ? *)
  createEvent:
    handler: src/custom.createEvent

resources:
  Outputs:
    CustomEventARN:
      Description: The ARN for the createEvent Lambda
      Value:
        "Fn::GetAtt": [ CreateEventLambdaFunction, Arn ]
      Export:
        Name: ${self:service}:${opt:stage}:CustomEventARN


custom:
  DYNAMODB: ${file(./../dynamodb/tables.js)}
