service: build-my-frontend

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-finch

custom:
  client:
    bucketName: ${file(./config.json):${opt:stage}.BUCKET_NAME}
    distributionFolder: build

